title: Michael Tao | Investment Banking Portfolio
description: >-
  Deal analysis, equity research, and DCF modelling.
  Applying for investment banking summer internships.
theme: minima
show_excerpts: true
